// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/clientStructure.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/clientStructure.proto

It has these top-level messages:
	Client
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Client struct {
	Id       int32          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name     string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email    string         `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Country2 string         `protobuf:"bytes,6,opt,name=country2" json:"country2,omitempty"`
	Inbox    []*Client_Mail `protobuf:"bytes,5,rep,name=inbox" json:"inbox,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Client) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Client) GetCountry2() string {
	if m != nil {
		return m.Country2
	}
	return ""
}

func (m *Client) GetInbox() []*Client_Mail {
	if m != nil {
		return m.Inbox
	}
	return nil
}

type Client_Mail struct {
	RemoteEmail string `protobuf:"bytes,1,opt,name=remoteEmail" json:"remoteEmail,omitempty"`
	Body        string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Client_Mail) Reset()                    { *m = Client_Mail{} }
func (m *Client_Mail) String() string            { return proto.CompactTextString(m) }
func (*Client_Mail) ProtoMessage()               {}
func (*Client_Mail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Client_Mail) GetRemoteEmail() string {
	if m != nil {
		return m.RemoteEmail
	}
	return ""
}

func (m *Client_Mail) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Client)(nil), "pb.Client")
	proto.RegisterType((*Client_Mail)(nil), "pb.Client.Mail")
}

func init() { proto.RegisterFile("pb/clientStructure.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0xab, 0x83, 0x30,
	0x14, 0x85, 0x49, 0x34, 0xf2, 0xde, 0x15, 0xde, 0x83, 0x4b, 0x87, 0xe0, 0x14, 0x0a, 0x05, 0xa7,
	0x14, 0xec, 0xda, 0xad, 0x74, 0xec, 0x62, 0x7f, 0x81, 0xd1, 0x0c, 0x01, 0x4d, 0x42, 0x88, 0x50,
	0x7f, 0x5f, 0xff, 0x58, 0x31, 0xd2, 0xd2, 0xed, 0x9c, 0xf3, 0xc1, 0x3d, 0xe7, 0x02, 0xf7, 0xea,
	0xd8, 0x8f, 0x46, 0xdb, 0x78, 0x8f, 0x61, 0xee, 0xe3, 0x1c, 0xb4, 0xf4, 0xc1, 0x45, 0x87, 0xd4,
	0xab, 0xfd, 0x93, 0x40, 0x71, 0x49, 0x14, 0xff, 0x80, 0x9a, 0x81, 0x13, 0x41, 0x6a, 0xd6, 0x52,
	0x33, 0x20, 0x42, 0x6e, 0xbb, 0x49, 0x73, 0x2a, 0x48, 0xfd, 0xdb, 0x26, 0x8d, 0x3b, 0x60, 0x7a,
	0xea, 0xcc, 0xc8, 0xb3, 0x14, 0x6e, 0x06, 0x2b, 0xf8, 0xe9, 0xdd, 0x6c, 0x63, 0x58, 0x1a, 0x5e,
	0x24, 0xf0, 0xf1, 0x78, 0x00, 0x66, 0xac, 0x72, 0x0f, 0xce, 0x44, 0x56, 0x97, 0xcd, 0xbf, 0xf4,
	0x4a, 0x6e, 0x85, 0xf2, 0xd6, 0x99, 0xb1, 0xdd, 0x68, 0x75, 0x86, 0x7c, 0xb5, 0x28, 0xa0, 0x0c,
	0x7a, 0x72, 0x51, 0x5f, 0x53, 0x0d, 0x49, 0xd7, 0xbe, 0xa3, 0x75, 0x96, 0x72, 0xc3, 0xf2, 0x9e,
	0xb5, 0x6a, 0x55, 0xa4, 0x87, 0x4e, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x30, 0xef, 0xc4,
	0xec, 0x00, 0x00, 0x00,
}
